Epytope switch in process peptide_prediction
nf-core/epitopeprediction pull request #148
Opened 2022-03-17 11:57 UTC by jonasscheid

The new release of epytope (v3.0.0) provides an altered prediction structure due to the incorporation of rank metrics.
This PR aims to embed the new prediction structure in the `epaa.py` script, which is called by the `PEPTIDE_PREDICTION` process.

Related issues:
#54 
#130

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/epitopeprediction _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-03-17 12:55 UTC, christopher-mohr commented
I will have a look. 👍 
Could you also please change conda and the containers in the process [here](https://github.com/nf-core/epitopeprediction/blob/8bb383c44383304c69557b4d00366384195918d5/modules/local/peptide_prediction.nf#L4). Should be `bioconda::epytope` and `quay.io/biocontainers/epytope`. I think you might have to specify the `tag` as well. If it works the test should pass as well.

2022-03-18 09:22 UTC, christopher-mohr commented
There was a permission problem with the bioconda container which is fixed now. The container can now be pulled from `http://quay.io/biocontainers/epytope:3.0.0--pyh5e36f6f_0`.

2022-03-18 10:26 UTC, christopher-mohr requested changes
Some things that need to be changed but overall it looks good. 👍

2022-03-18 10:26 UTC, christopher-mohr commented on bin/epaa.py
> -            return round(j, 4)
might make sense to keep the `round` for the scores column to get the same results as before.

2022-03-18 10:26 UTC, christopher-mohr commented on bin/epaa.py
> +        #df.insert(2, 'length', df['sequence'].map(len))
can be removed I guess?

2022-03-18 11:37 UTC, jonasscheid commented on bin/epaa.py
> -def create_score_values(j, method):
As discussed, epytope returns score values for all predictors. Therefore, the method is not needed anymore. Values are rounded in a different step

2022-03-18 11:37 UTC, jonasscheid commented on bin/epaa.py
> -                            if not getattr(sample.data, format_key, None):
Yep, will add it again.

2022-03-18 11:38 UTC, jonasscheid commented on bin/epaa.py
> -        elif any(m in method for m in ['mhcnuggets','mhcflurry']):
See above

2022-03-18 12:10 UTC, christopher-mohr approved these changes
LGTM! Some of the tests are failing because of an `epytope` issue which will be solved in the new release.

2022-03-18 12:11 UTC, merged