Release 2.3.0
nf-core/epitopeprediction pull request #230
Opened 2024-02-14 10:02 UTC by jonasscheid

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/epitopeprediction _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-02-17 07:55 UTC, christopher-mohr commented
I just removed the "old" CI tests from the required checks

2024-02-17 08:18 UTC, christopher-mohr reviewed
A couple of suggestions so far, I will continue later.

2024-02-17 08:18 UTC, christopher-mohr commented on assets/schema_input.json
> +                "errorMessage": "Variants/proteins/peptides for sample must be provided and have one of the following extensions: '.vcf', '.vcf.gz', '.tsv', '.fasta', '.fa'"
```suggestion
                "errorMessage": "Variants/proteins/peptides of a sample must be provided and have one of the following extensions: '.vcf', '.vcf.gz', '.tsv', '.fasta', '.fa'"
```

2024-02-17 08:18 UTC, christopher-mohr commented on docs/usage.md
> +> Please note that genomic variants have to be annotated. Currently, we support variants that have been annotated using [SnpEff](http://pcingola.> github.io/SnpEff/).
```suggestion
> Please note that genomic variants have to be annotated. Currently, we support variants that have been annotated using [SnpEff](http://pcingola.> github.io/SnpEff/) and [VEP](https://www.ensembl.org/info/docs/tools/vep/index.html).
```

2024-02-17 08:18 UTC, christopher-mohr commented on docs/usage.md
> +> Support for [VEP](https://www.ensembl.org/info/docs/tools/vep/index.html) will be available with one of the upcoming versions.
```suggestion
```

2024-02-17 08:18 UTC, christopher-mohr commented on docs/usage.md
> +For genomic variants, reference information from `Ensembl BioMart` is used. The default database version is the most recent `GRCh37` version. If you want to do the predictions based on `GRCh38` as th
```suggestion
For genomic variants, reference information from `Ensembl BioMart` is used. The default database version is the most recent `GRCh37` version. If you want to do the predictions based on `GRCh38` as the reference genome, please specify `--genome_reference grch38` in your pipeline call.
```

2024-02-17 08:18 UTC, christopher-mohr commented on lib/WorkflowEpitopeprediction.groovy
> +                "FastQC (Andrews 2010),",
```suggestion
```

2024-02-19 16:19 UTC, christopher-mohr reviewed
Some additional comments/suggestions

2024-02-19 16:19 UTC, christopher-mohr commented on bin/check_requested_models.py
> +    if args.alleles.startswith("http"):
Not needed in this context since input should be string only.

2024-02-19 16:19 UTC, christopher-mohr commented on bin/check_requested_models.py
> +        alleles = [Allele(a) for a in args.alleles.split(";")]
```suggestion
alleles = [Allele(a) for a in args.alleles.split(";")]
```

2024-02-19 16:19 UTC, christopher-mohr commented on CHANGELOG.md
> +- [#227](https://github.com/nf-core/epitopeprediction/pull/227) Prevent crash if no transcript is found (in splitted vcf)
```suggestion
- [#227](https://github.com/nf-core/epitopeprediction/pull/227) - Prevent crash if no transcript is found (in splitted vcf)
```

2024-02-19 23:31 UTC, jonasscheid commented on .nf-core.yml
I tried this as well, but did not work here somehow. Will be handled already differently in the upcoming tools version afaik, so agree to skip it 👍🏼

2024-02-20 14:34 UTC, mapo9 requested changes
looks very nice!
Only some minor stuff

2024-02-20 14:34 UTC, mapo9 commented on docs/usage.md
> +The supported file formats for genomic variants are `.vcf`, `.vcf.gz` and `tsv`.
remove `tsv` here.

2024-02-20 14:34 UTC, mapo9 commented on docs/usage.md
> +To further assist in reproducbility, you can use share and re-use [parameter files](#running-the-pipeline) to repeat pipeline runs with the same settings without having to write out a command with ev
```suggestion
To further assist in reproducibility, you can use share and re-use [parameter files](#running-the-pipeline) to repeat pipeline runs with the same settings without having to write out a command with every single parameter.
```

2024-02-20 14:34 UTC, mapo9 commented on docs/usage.md
> +If you wish to share such profile (such as upload as supplementary material for academic publications), make sure to NOT include cluster specific paths to files, nor institutional specific profiles.
```suggestion
If you wish to share such profile (such as upload as supplementary material for academic publications), make sure NOT to include cluster specific paths to files, nor institution specific profiles.
```

2024-02-20 14:34 UTC, mapo9 commented on nextflow.config
I think best practice would be to have all the `=`at the same tab position?

2024-02-20 14:34 UTC, mapo9 commented on nextflow_schema.json
> +                    "help_text": "If using a reference genome configured in the pipeline using iGenomes, use this parameter to give the ID for the reference. This is then used to build the full paths
```suggestion
                    "help_text": "If using a reference genome configured in the pipeline using iGenomes, use this parameter to give the ID for the reference. This is then used to build the full paths for all required reference genome files e.g. `--genome GRCh38`.\n\nSee the [nf-core website docs](https://nf-co.re/usage/reference_genomes) for more details."
```

2024-02-20 14:34 UTC, mapo9 commented on nextflow_schema.json
> +                "fasta": {
dont think you guys use this?

2024-02-23 10:20 UTC, christopher-mohr commented
Let's get another review for this because once tests pass because of the most recent template change.

2024-02-23 12:20 UTC, mapo9 approved these changes
LGTM! 🚀 

just one minor change to improve readability of a parameter

2024-02-23 12:42 UTC, christopher-mohr approved these changes
LGTM

2024-02-26 11:49 UTC, merged