Merge template updates up to 2.14.1
nf-core/epitopeprediction pull request #243
Opened 2024-05-15 06:46 UTC by christopher-mohr

Merging the last two template updates.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/epitopeprediction _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-05-15 07:06 UTC, christopher-mohr commented
Ensembl most recent BioMart version currently unavailable, therefore the `grch38` test fails:

``` 
Server Status
The Ensembl websites and REST servers are currently unavailable as we apply updates. Our archive sites, FTP site and public MySQL servers are unaffected. Please try again shortly.
```

2024-05-15 07:14 UTC, jonasscheid requested changes
LGTM, thanks! Only adjusting the changelog date and name remains

2024-05-15 07:24 UTC, christopher-mohr commented
> LGTM, thanks! Only adjusting the changelog date and name remains

I will still check the issue with GRCH38 which does not seem to be (solely) caused by the Ensembl unavailability.

2024-05-15 11:55 UTC, christopher-mohr commented
In the meantime, Ensembl replied and confirmed that there are currently some issues with the most recent BioMart version. What happened is that the protein field/table we are using to retrieve protein information was/is currently not accessible and therefore no information is available in the df. 

I added a check to make sure that the information is only accessed if available.

2024-05-16 06:15 UTC, christopher-mohr commented on bin/epaa.py
> +        return ""
added

2024-05-16 07:52 UTC, merged