Add functionality to write fasta with protein sequences
nf-core/epitopeprediction pull request #57
Opened 2020-09-11 12:59 UTC by christopher-mohr

Add functionality to write out a FASTA file with protein sequences as mentioned in #33 

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/epitopeprediction branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/epitopeprediction)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md

2020-09-14 08:05 UTC, skrakau requested changes
Hi, great that you added this! It is addressing https://github.com/nf-core/epitopeprediction/issues/9 (not https://github.com/nf-core/epitopeprediction/pull/33, although both dealing with FASTAs). I added a few comments.

Could you additionally add a description to the `docs/output.md`? 

And if I see it right, this option only works (and makes sense) with variants as input, i.e. not with `--peptides` or `--proteins`. Maybe it would be useful to check at the beginning of the pipline if the parameter combination is valid and throw an error if not. Also this could be mentioned in the help/schema description of this parameter.

2020-09-14 08:08 UTC, christopher-mohr commented
> Hi, great that you added this! It is addressing #9 (not #33, although both dealing with FASTAs). I added a few comments.

Right, changed it! 👍

2020-09-14 09:13 UTC, christopher-mohr commented
Thanks for the review @skrakau! Hope you're happy with the changes :)

2020-09-15 07:24 UTC, skrakau requested changes
Looks good, just one tiny detail is still missing ;)

2020-09-15 07:24 UTC, skrakau commented on docs/output.md
> +When the parameter `--fasta_output` is specified a `FASTA` file will be generated that contains the sequences of proteins that are affected by the provided genomic variants. The resulting `FASTA` fil
In which folder will this be located, and how will it be called?

2020-09-16 08:12 UTC, christopher-mohr commented
The last commit includes more changes than initially planned ;):

- merge FASTA files in case of splitted results 
- fixed the statistics for single and multiple (splitter) results
- include input base name in result files
- change result folder name
- update docs

2020-09-17 16:03 UTC, skrakau requested changes
Looks good! :) 

Just one remaining inconsistency in the notation of output files.

2020-09-17 16:03 UTC, skrakau commented on docs/output.md
> +* `${input_base_name}_prediction_report.json`
This is inconsistent with the notation used for `[tool].[version].supported_alleles.txt`. Seems every pipeline does this differently. Use either `[...]` or `${...}` in the whole `output.md`.

2020-09-17 16:03 UTC, skrakau commented on docs/output.md
> +* `${input_base_name}_prediction_results.tsv`
See above.

2020-09-17 16:03 UTC, skrakau commented on docs/output.md
> +* `${input_base_name}_prediction_proteins.fasta`
See above.

2020-09-18 07:53 UTC, skrakau approved these changes
LGTM @christopher-mohr

2020-09-18 07:55 UTC, christopher-mohr commented
> LGTM @christopher-mohr

Thank you @skrakau !

2020-09-18 07:55 UTC, merged