Release 1.1.0
nf-core/epitopeprediction pull request #63
Opened 2020-10-09 12:18 UTC by christopher-mohr

PR for the next release (`1.1.0`).

We will take care of the full test dataset in the next release.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/epitopeprediction branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/epitopeprediction)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [x] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md

2020-10-12 12:19 UTC, skrakau requested changes
Looks good! Just a few minor changes and questions.

2020-10-14 09:50 UTC, christopher-mohr commented on bin/epaa.py
> +            return max(0, round(((100.0 / float(max_scores[allele_strings[('%s_%s' % (str(allele), length))]]) * float(j)) / 100.0) * 100, 2))
True 👍

2020-10-14 10:12 UTC, christopher-mohr commented on docs/output.md
> +  * **Affinity**: Calculated as the half-max score of the corresponding matrix: `score(peptide) divided by the maximum score of the allele/length-specific matrix * 100`.
Not sure if I understand this correctly but this line in `epaa.py` corresponds to the half-max score: 
`max_scores[allele_strings[('%s_%s' % (str(allele), length))]]`

The values are calculated by this function:
```
def get_matrix_max_score(allele, length):
    allele_model = "%s_%i" % (allele, length)
    try:
        pssm = getattr(__import__("Fred2.Data.pssms.syfpeithi.mat."+allele_model, fromlist=[allele_model]),
                           allele_model)
        return sum([max(scrs.values()) for pos, scrs in pssm.iteritems()])
    except:
        return np.nan
``` 

This isn't an affinity (or IC50).

2020-10-19 11:01 UTC, skrakau approved these changes
Looks great!

2020-10-19 11:02 UTC, skrakau commented
The release date in the CHANGELOG should be updated when everything else is settled.

2020-10-19 14:17 UTC, ggabernet requested changes

2020-10-19 14:17 UTC, ggabernet commented on .github/workflows/awstest.yml
> +          --container-overrides '{"command": ["nf-core/epitopeprediction", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/epitopeprediction/results-'"${GITHUB_SHA}"' -w s3://'
```suggestion
          --container-overrides '{"command": ["nf-core/epitopeprediction", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/epitopeprediction/results-'"${GITHUB_SHA}"' -w s3://'"${AWS_S3_BUCKET}"'/epitopeprediction/work-'"${GITHUB_SHA}"' -with-tower"], "environment": [{"name": "TOWER_ACCESS_TOKEN", "value": "'"$TOWER_ACCESS_TOKEN"'"}]}'
```

2020-10-19 14:17 UTC, ggabernet commented on .github/workflows/awstest.yml
> +          --container-overrides '{"command": ["nf-core/epitopeprediction", "-r '"${GITHUB_SHA}"' -profile test --outdir s3://'"${AWS_S3_BUCKET}"'/epitopeprediction/results-'"${GITHUB_SHA}"' -w s3://'
There is still this issue in the Awstest :)

2020-10-19 14:17 UTC, ggabernet commented on README.md
> +[![DOI](TODO)](todo)
```suggestion
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3564666.svg)](https://doi.org/10.5281/zenodo.3564666)```

2020-10-19 14:17 UTC, ggabernet commented on README.md
> +[![DOI](TODO)](todo)
The DOI already exists https://doi.org/10.5281/zenodo.3564666

2020-10-19 14:17 UTC, ggabernet commented on README.md
> +[![DOI](TODO)](todo)
```suggestion
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3564666.svg)](https://doi.org/10.5281/zenodo.3564666)
```

2020-10-19 14:17 UTC, ggabernet commented on README.md
> +[![DOI](TODO)](todo)
The badge already exists ;)

2020-10-19 14:31 UTC, ggabernet approved these changes
Ah I don't know what happened that it was not updated. Looks good now!

2020-10-20 07:22 UTC, christopher-mohr commented
Thanks @skrakau and @ggabernet!

2020-10-20 11:01 UTC, christopher-mohr commented on CHANGELOG.md
> +## v1.1.0 - 2020-10-09
```suggestion
## v1.1.0 - Morgenstelle - 2020-10-20
```

2020-10-20 12:09 UTC, merged